### ISSUE TITLE
Translation file is empty

### ISSUE THREAD

**Issue by drak25** [mageplaza/magento-2-polish-language-pack#3]
The translation file has been cleared on Apr 8, 2019. Why is that ?

**Comment by legendhorus** [comment]
Thanks for your report and sorry for any inconvenience.
We have fixed this issue. Please update the latest version or rollback to previous.

Magento removed a server related to Crowdin.
We have build a new server to resolve the problem.

To help Magento community, feel free to translate this language pack in Crowdin
